<template>
  <div class="audit-page">
    <PageHeader title="操作审计" description="记录敏感数据访问、权限与招聘操作"><template #actions><el-button @click="fetchList">刷新</el-button></template></PageHeader>
    <el-card shadow="never" class="filter-card"><el-form inline @submit.prevent><el-form-item label="关键词"><el-input v-model="filters.keyword" placeholder="成员姓名或对象" clearable @keyup.enter="handleSearch" /></el-form-item><el-form-item label="操作"><el-select v-model="filters.action" clearable placeholder="全部操作"><el-option v-for="item in actions" :key="item.value" :label="item.label" :value="item.value" /></el-select></el-form-item><el-form-item label="时间范围"><el-date-picker v-model="filters.dateRange" type="daterange" value-format="YYYY-MM-DD" start-placeholder="开始日期" end-placeholder="结束日期" /></el-form-item><el-form-item label="对象"><el-input v-model="filters.targetType" placeholder="候选人、Offer 等" clearable @keyup.enter="handleSearch" /></el-form-item><el-form-item><el-button type="primary" @click="handleSearch">查询</el-button><el-button @click="handleReset">重置</el-button></el-form-item></el-form></el-card>
    <el-card shadow="never" v-loading="loading"><el-table :data="list" stripe><el-table-column label="时间／成员" min-width="180"><template #default="{ row }"><strong>{{ formatDate(row.createdAt) }}</strong><div class="sub">{{ row.user?.name || '系统' }} · {{ row.user?.email || '自动任务' }}</div></template></el-table-column><el-table-column label="操作" width="160"><template #default="{ row }"><el-tag effect="plain">{{ actionLabel(row.action) }}</el-tag></template></el-table-column><el-table-column label="对象" min-width="170"><template #default="{ row }"><strong>{{ row.targetType || '未分类' }}</strong><div class="sub">{{ row.targetId || '—' }}</div></template></el-table-column><el-table-column label="详情" min-width="220" show-overflow-tooltip><template #default="{ row }">{{ formatDetail(row.detail) }}</template></el-table-column></el-table><el-empty v-if="!loading && !list.length" description="暂无审计记录" /><div class="pagination-wrapper"><el-pagination v-model:current-page="pagination.page" :page-size="pagination.pageSize" :total="pagination.total" layout="total, prev, pager, next" @current-change="fetchList" /></div></el-card>
  </div>
</template>
<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'; import { ElMessage } from 'element-plus'; import PageHeader from '@/components/common/PageHeader.vue'; import { getAuditLogs, type AuditLogItem } from '@/api/audit-log';
const list = ref<AuditLogItem[]>([]); const loading = ref(false); const actions = [{ value: 'resume_view', label: '查看简历' }, { value: 'resume_download', label: '下载简历' }, { value: 'offer_approved', label: '审批通过 Offer' }, { value: 'offer_rejected', label: '驳回 Offer' }, { value: 'candidate_anonymized', label: '候选人匿名化' }, { value: 'updated', label: '更新记录' }, { value: 'deleted', label: '删除记录' }];
const filters = reactive({ keyword: '', action: '', targetType: '', dateRange: [] as string[] }); const pagination = reactive({ page: 1, pageSize: 20, total: 0, totalPages: 0 });
async function fetchList() { loading.value = true; try { const res = await getAuditLogs({ page: pagination.page, pageSize: pagination.pageSize, keyword: filters.keyword || undefined, action: filters.action || undefined, targetType: filters.targetType || undefined, startDate: filters.dateRange[0], endDate: filters.dateRange[1] }); if (res.success) { list.value = res.data; Object.assign(pagination, res.pagination); } } catch (error: unknown) { ElMessage.error(error instanceof Error ? error.message : '加载审计记录失败'); } finally { loading.value = false; } }
function handleSearch() { pagination.page = 1; fetchList(); } function handleReset() { Object.assign(filters, { keyword: '', action: '', targetType: '', dateRange: [] }); handleSearch(); } function actionLabel(action: string) { return actions.find((item) => item.value === action)?.label || action; } function formatDate(value: string) { return new Date(value).toLocaleString('zh-CN', { hour12: false }); } function formatDetail(detail: unknown) { if (!detail) return '—'; if (typeof detail === 'string') return detail; if (typeof detail === 'object') { const entries = Object.entries(detail as Record<string, unknown>).slice(0, 3); return entries.map(([key, value]) => `${key}: ${String(value)}`).join(' · '); } return String(detail); } onMounted(fetchList);
</script>
<style scoped lang="scss">.audit-page { max-width: 1280px; margin: 0 auto; padding: 4px 0 20px; }.filter-card { margin-bottom: 16px; }.sub { margin-top: 4px; color: $ui-gray-500; font-size: 12px; }.pagination-wrapper { display: flex; justify-content: flex-end; margin-top: 16px; }</style>
