packages:
  - 'client'
  - 'server'
  - 'mobile'
allowBuilds:
  '@parcel/watcher': true
  '@prisma/client': true
  '@prisma/engines': true
  '@scarf/scarf': false
  cpu-features: false
  esbuild: true
  msgpackr-extract: false
  prisma: true
  protobufjs: false
  ssh2: false
  vue-demi: true
